program TestApplication;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  Quick.Amazon in 'Quick.Amazon.pas',
  Quick.AppService in 'Quick.AppService.pas',
  Quick.Arrays.Helper in 'Quick.Arrays.Helper.pas',
  Quick.Arrays in 'Quick.Arrays.pas',
  Quick.AutoMapper in 'Quick.AutoMapper.pas',
  Quick.Azure in 'Quick.Azure.pas',
  Quick.Base64 in 'Quick.Base64.pas',
  Quick.Cache.Intf in 'Quick.Cache.Intf.pas',
  Quick.Chrono in 'Quick.Chrono.pas',
  Quick.CloudStorage in 'Quick.CloudStorage.pas',
  Quick.CloudStorage.Provider.Amazon in 'Quick.CloudStorage.Provider.Amazon.pas',
  Quick.CloudStorage.Provider.Azure in 'Quick.CloudStorage.Provider.Azure.pas',
  Quick.Collections in 'Quick.Collections.pas',
  Quick.Commons in 'Quick.Commons.pas',
  Quick.Compression.LZO in 'Quick.Compression.LZO.pas',
  Quick.Compression in 'Quick.Compression.pas',
  Quick.Conditions in 'Quick.Conditions.pas',
  Quick.Config.Base in 'Quick.Config.Base.pas',
  Quick.Config.Json in 'Quick.Config.Json.pas',
  Quick.Config.Registry in 'Quick.Config.Registry.pas',
  Quick.Config.YAML in 'Quick.Config.YAML.pas',
  Quick.Console in 'Quick.Console.pas',
  Quick.Crypto in 'Quick.Crypto.pas',
  Quick.Data.Custom in 'Quick.Data.Custom.pas',
  Quick.Data.InfluxDB in 'Quick.Data.InfluxDB.pas',
  Quick.Data.Redis in 'Quick.Data.Redis.pas',
  Quick.Debug.Utils in 'Quick.Debug.Utils.pas',
  Quick.Expression in 'Quick.Expression.pas',
  Quick.FaultControl in 'Quick.FaultControl.pas',
  Quick.FileMonitor in 'Quick.FileMonitor.pas',
  Quick.Files in 'Quick.Files.pas',
  Quick.Format in 'Quick.Format.pas',
  Quick.HttpClient in 'Quick.HttpClient.pas',
  Quick.HttpServer in 'Quick.HttpServer.pas',
  Quick.HttpServer.Request in 'Quick.HttpServer.Request.pas',
  Quick.HttpServer.Response in 'Quick.HttpServer.Response.pas',
  Quick.HttpServer.Types in 'Quick.HttpServer.Types.pas',
  Quick.IOC in 'Quick.IOC.pas',
  Quick.JSON.Helper in 'Quick.JSON.Helper.pas',
  Quick.Json.Serializer in 'Quick.Json.Serializer.pas',
  Quick.JSON.Utils in 'Quick.JSON.Utils.pas',
  Quick.JSONRecord in 'Quick.JSONRecord.pas',
  Quick.Linq in 'Quick.Linq.pas',
  Quick.Lists in 'Quick.Lists.pas',
  Quick.Log in 'Quick.Log.pas',
  Quick.Logger.Intf in 'Quick.Logger.Intf.pas',
  Quick.Mapper.Intf in 'Quick.Mapper.Intf.pas',
  Quick.MemoryCache.Compressor.GZip in 'Quick.MemoryCache.Compressor.GZip.pas',
  Quick.MemoryCache.Compressor.LZO in 'Quick.MemoryCache.Compressor.LZO.pas',
  Quick.MemoryCache in 'Quick.MemoryCache.pas',
  Quick.MemoryCache.Serializer.Json in 'Quick.MemoryCache.Serializer.Json.pas',
  Quick.MemoryCache.Types in 'Quick.MemoryCache.Types.pas',
  Quick.Network in 'Quick.Network.pas',
  Quick.OAuth in 'Quick.OAuth.pas',
  Quick.OAuth.Utils in 'Quick.OAuth.Utils.pas',
  Quick.Options in 'Quick.Options.pas',
  Quick.Options.Serializer.Json in 'Quick.Options.Serializer.Json.pas',
  Quick.Options.Serializer.Yaml in 'Quick.Options.Serializer.Yaml.pas',
  Quick.Parameters in 'Quick.Parameters.pas',
  Quick.Pooling in 'Quick.Pooling.pas',
  Quick.Process in 'Quick.Process.pas',
  Quick.RegEx.Utils in 'Quick.RegEx.Utils.pas',
  Quick.Registry in 'Quick.Registry.pas',
  Quick.RTTI.Utils in 'Quick.RTTI.Utils.pas',
  Quick.Serializer.Intf in 'Quick.Serializer.Intf.pas',
  Quick.Service in 'Quick.Service.pas',
  Quick.SMTP in 'Quick.SMTP.pas',
  Quick.SyncObjs.Linux.Compatibility in 'Quick.SyncObjs.Linux.Compatibility.pas',
  Quick.SysInfo in 'Quick.SysInfo.pas',
  Quick.Template in 'Quick.Template.pas',
  Quick.Threads in 'Quick.Threads.pas',
  Quick.Url.Utils in 'Quick.Url.Utils.pas',
  Quick.Value in 'Quick.Value.pas',
  Quick.Value.RTTI in 'Quick.Value.RTTI.pas',
  Quick.WebBrowser in 'Quick.WebBrowser.pas',
  Quick.WMI in 'Quick.WMI.pas',
  Quick.YAML in 'Quick.YAML.pas',
  Quick.YAML.Serializer in 'Quick.YAML.Serializer.pas',
  WbemScripting_TLB in 'WbemScripting_TLB.pas';

begin
  try
    { TODO -oUser -cConsole Main : Insert code here }
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
